import type {
  EditablePropertyDefinition,
  EditablePropertyGroupId,
  EditablePropertyId,
} from './types';

export const editablePropertyDefinitions = [
  {
    id: 'paddingTop',
    label: 'Padding top',
    shortLabel: 'PT',
    cssProperty: 'padding-top',
    group: 'spacing',
    control: 'text',
    placeholder: '16px',
  },
  {
    id: 'paddingRight',
    label: 'Padding right',
    shortLabel: 'PR',
    cssProperty: 'padding-right',
    group: 'spacing',
    control: 'text',
    placeholder: '16px',
  },
  {
    id: 'paddingBottom',
    label: 'Padding bottom',
    shortLabel: 'PB',
    cssProperty: 'padding-bottom',
    group: 'spacing',
    control: 'text',
    placeholder: '16px',
  },
  {
    id: 'paddingLeft',
    label: 'Padding left',
    shortLabel: 'PL',
    cssProperty: 'padding-left',
    group: 'spacing',
    control: 'text',
    placeholder: '16px',
  },
  {
    id: 'marginTop',
    label: 'Margin top',
    shortLabel: 'MT',
    cssProperty: 'margin-top',
    group: 'spacing',
    control: 'text',
    placeholder: '8px',
  },
  {
    id: 'marginRight',
    label: 'Margin right',
    shortLabel: 'MR',
    cssProperty: 'margin-right',
    group: 'spacing',
    control: 'text',
    placeholder: '8px',
  },
  {
    id: 'marginBottom',
    label: 'Margin bottom',
    shortLabel: 'MB',
    cssProperty: 'margin-bottom',
    group: 'spacing',
    control: 'text',
    placeholder: '8px',
  },
  {
    id: 'marginLeft',
    label: 'Margin left',
    shortLabel: 'ML',
    cssProperty: 'margin-left',
    group: 'spacing',
    control: 'text',
    placeholder: '8px',
  },
  {
    id: 'borderRadius',
    label: 'Border radius',
    shortLabel: 'Radius',
    cssProperty: 'border-radius',
    group: 'radius',
    control: 'text',
    placeholder: '12px',
  },
  {
    id: 'backgroundColor',
    label: 'Background color',
    shortLabel: 'BG',
    cssProperty: 'background-color',
    group: 'color',
    control: 'text',
    placeholder: 'rgb(255, 255, 255)',
  },
  {
    id: 'color',
    label: 'Text color',
    shortLabel: 'Text',
    cssProperty: 'color',
    group: 'color',
    control: 'text',
    placeholder: 'rgb(17, 24, 39)',
  },
  {
    id: 'fontSize',
    label: 'Font size',
    shortLabel: 'Size',
    cssProperty: 'font-size',
    group: 'typography',
    control: 'text',
    placeholder: '16px',
  },
  {
    id: 'fontWeight',
    label: 'Font weight',
    shortLabel: 'Weight',
    cssProperty: 'font-weight',
    group: 'typography',
    control: 'text',
    placeholder: '600',
  },
  {
    id: 'lineHeight',
    label: 'Line height',
    shortLabel: 'Leading',
    cssProperty: 'line-height',
    group: 'typography',
    control: 'text',
    placeholder: '24px',
  },
  {
    id: 'opacity',
    label: 'Opacity',
    shortLabel: 'Opacity',
    cssProperty: 'opacity',
    group: 'opacity',
    control: 'opacity',
    placeholder: '0.8',
  },
] satisfies EditablePropertyDefinition[];

export const editablePropertyDefinitionMap = Object.fromEntries(
  editablePropertyDefinitions.map((definition) => [definition.id, definition])
) as Record<EditablePropertyId, EditablePropertyDefinition>;

export const editablePropertyGroupOrder = [
  'spacing',
  'radius',
  'color',
  'typography',
  'opacity',
] as const satisfies EditablePropertyGroupId[];

export const editablePropertyGroupLabels: Record<EditablePropertyGroupId, string> = {
  spacing: 'Spacing',
  radius: 'Radius',
  color: 'Color',
  typography: 'Typography',
  opacity: 'Opacity',
};
