import type {
  EditablePropertyDefinition,
  EditablePropertyGroupId,
  EditablePropertyId,
  FocusedGroupId,
} from './types';

export const editablePropertyDefinitions = [
  // ── Position ──────────────────────────────────────────────────────────
  {
    id: 'positionType',
    label: 'Position',
    shortLabel: 'Pos',
    cssProperty: 'position',
    group: 'position',
    control: 'select',
    placeholder: 'relative',
    options: [
      { label: 'Static', value: 'static',
  hiddenInV1: true },
      { label: 'Relative', value: 'relative' },
      { label: 'Absolute', value: 'absolute' },
      { label: 'Fixed', value: 'fixed' },
      { label: 'Sticky', value: 'sticky' },
    ],
    tailwindPrefix: 'position',
  },
  {
    id: 'top',
    label: 'Top',
    shortLabel: 'T',
    cssProperty: 'top',
    group: 'position',
    control: 'number',
    placeholder: '0px',
    units: ['px', 'rem', '%', 'auto'],
    defaultUnit: 'px',
    tailwindPrefix: 'top',
  hiddenInV1: true,
  },
  {
    id: 'right',
    label: 'Right',
    shortLabel: 'R',
    cssProperty: 'right',
    group: 'position',
    control: 'number',
    placeholder: '0px',
    units: ['px', 'rem', '%', 'auto'],
    defaultUnit: 'px',
    tailwindPrefix: 'right',
  hiddenInV1: true,
  },
  {
    id: 'bottom',
    label: 'Bottom',
    shortLabel: 'B',
    cssProperty: 'bottom',
    group: 'position',
    control: 'number',
    placeholder: '0px',
    units: ['px', 'rem', '%', 'auto'],
    defaultUnit: 'px',
    tailwindPrefix: 'bottom',
  hiddenInV1: true,
  },
  {
    id: 'left',
    label: 'Left',
    shortLabel: 'L',
    cssProperty: 'left',
    group: 'position',
    control: 'number',
    placeholder: '0px',
    units: ['px', 'rem', '%', 'auto'],
    defaultUnit: 'px',
    tailwindPrefix: 'left',
  hiddenInV1: true,
  },
  {
    id: 'zIndex',
    label: 'Z-Index',
    shortLabel: 'Z',
    cssProperty: 'z-index',
    group: 'position',
    control: 'number',
    placeholder: '0',
    tailwindPrefix: 'z',
  hiddenInV1: true,
  },

  // ── Auto Layout (Flexbox / Grid) ─────────────────────────────────────
  {
    id: 'display',
    label: 'Display',
    shortLabel: 'Visible',
    cssProperty: 'display',
    group: 'autoLayout',
    control: 'toggle',
    placeholder: 'block',
    options: [
      { label: 'Visible', value: 'block' },
      { label: 'Hide', value: 'none' },
    ],
    tailwindPrefix: 'display',
  },
  {
    id: 'flexDirection',
    label: 'Direction',
    shortLabel: 'Dir',
    cssProperty: 'flex-direction',
    group: 'autoLayout',
    control: 'segmented',
    placeholder: 'row',
    options: [
      { label: 'Row', value: 'row',
  hiddenInV1: true },
      { label: 'Col', value: 'column' },
      { label: 'Row-R', value: 'row-reverse' },
      { label: 'Col-R', value: 'column-reverse' },
    ],
    tailwindPrefix: 'flex',
  },
  {
    id: 'flexWrap',
    label: 'Wrap',
    shortLabel: 'Wrap',
    cssProperty: 'flex-wrap',
    group: 'autoLayout',
    control: 'segmented',
    placeholder: 'nowrap',
    options: [
      { label: 'No Wrap', value: 'nowrap',
  hiddenInV1: true },
      { label: 'Wrap', value: 'wrap' },
      { label: 'Reverse', value: 'wrap-reverse' },
    ],
    tailwindPrefix: 'flex',
  },
  {
    id: 'justifyContent',
    label: 'Justify',
    shortLabel: 'Justify',
    cssProperty: 'justify-content',
    group: 'autoLayout',
    control: 'segmented',
    placeholder: 'flex-start',
    options: [
      { label: 'Start', value: 'flex-start',
  hiddenInV1: true },
      { label: 'Center', value: 'center' },
      { label: 'End', value: 'flex-end' },
      { label: 'Between', value: 'space-between' },
    ],
    tailwindPrefix: 'justify',
  },
  {
    id: 'alignItems',
    label: 'Align',
    shortLabel: 'Align',
    cssProperty: 'align-items',
    group: 'autoLayout',
    control: 'segmented',
    placeholder: 'stretch',
    options: [
      { label: 'Start', value: 'flex-start',
  hiddenInV1: true },
      { label: 'Center', value: 'center' },
      { label: 'End', value: 'flex-end' },
      { label: 'Stretch', value: 'stretch' },
    ],
    tailwindPrefix: 'items',
  },
  {
    id: 'alignSelf',
    label: 'Align self',
    shortLabel: 'Self',
    cssProperty: 'align-self',
    group: 'autoLayout',
    control: 'select',
    placeholder: 'auto',
    options: [
      { label: 'Auto', value: 'auto',
  hiddenInV1: true },
      { label: 'Start', value: 'flex-start' },
      { label: 'Center', value: 'center' },
      { label: 'End', value: 'flex-end' },
      { label: 'Stretch', value: 'stretch' },
    ],
    tailwindPrefix: 'self',
  },
  {
    id: 'gap',
    label: 'Gap',
    shortLabel: 'Gap',
    cssProperty: 'gap',
    group: 'autoLayout',
    control: 'number',
    placeholder: '16px',
    units: ['px', 'rem'],
    defaultUnit: 'px',
    tailwindPrefix: 'gap',
  hiddenInV1: true,
  },
  {
    id: 'rowGap',
    label: 'Row gap',
    shortLabel: 'R-Gap',
    cssProperty: 'row-gap',
    group: 'autoLayout',
    control: 'number',
    placeholder: '16px',
    units: ['px', 'rem'],
    defaultUnit: 'px',
    tailwindPrefix: 'gap-y',
  hiddenInV1: true,
  },
  {
    id: 'columnGap',
    label: 'Column gap',
    shortLabel: 'C-Gap',
    cssProperty: 'column-gap',
    group: 'autoLayout',
    control: 'number',
    placeholder: '16px',
    units: ['px', 'rem'],
    defaultUnit: 'px',
    tailwindPrefix: 'gap-x',
  hiddenInV1: true,
  },
  {
    id: 'gridColumns',
    label: 'Columns',
    shortLabel: 'Cols',
    cssProperty: 'grid-template-columns',
    group: 'autoLayout',
    control: 'number',
    placeholder: '3',
    tailwindPrefix: 'grid-cols',
    cssTransform: 'repeat({value}, 1fr)',
    hiddenInV1: true,
  },
  {
    id: 'gridRows',
    label: 'Rows',
    shortLabel: 'Rows',
    cssProperty: 'grid-template-rows',
    group: 'autoLayout',
    control: 'number',
    placeholder: '2',
    tailwindPrefix: 'grid-rows',
    cssTransform: 'repeat({value}, 1fr)',
    hiddenInV1: true,
  },
  {
    id: 'flexGrow',
    label: 'Grow',
    shortLabel: 'Grow',
    cssProperty: 'flex-grow',
    group: 'autoLayout',
    control: 'number',
    placeholder: '0',
    min: 0,
    tailwindPrefix: 'grow',
  hiddenInV1: true,
  },
  {
    id: 'flexShrink',
    label: 'Shrink',
    shortLabel: 'Shrink',
    cssProperty: 'flex-shrink',
    group: 'autoLayout',
    control: 'number',
    placeholder: '1',
    min: 0,
    tailwindPrefix: 'shrink',
  hiddenInV1: true,
  },
  {
    id: 'flexBasis',
    label: 'Basis',
    shortLabel: 'Basis',
    cssProperty: 'flex-basis',
    group: 'autoLayout',
    control: 'number',
    placeholder: 'auto',
    units: ['px', 'rem', '%', 'auto'],
    defaultUnit: 'px',
    tailwindPrefix: 'basis',
  hiddenInV1: true,
  },
  {
    id: 'gridAutoFlow',
    label: 'Auto flow',
    shortLabel: 'Flow',
    cssProperty: 'grid-auto-flow',
    group: 'autoLayout',
    control: 'select',
    placeholder: 'row',
    options: [
      { label: 'Row', value: 'row',
  hiddenInV1: true },
      { label: 'Column', value: 'column' },
      { label: 'Dense', value: 'dense' },
      { label: 'Row dense', value: 'row dense' },
      { label: 'Column dense', value: 'column dense' },
    ],
    tailwindPrefix: 'auto-flow',
  },
  {
    id: 'columnSpan',
    label: 'Column span',
    shortLabel: 'Col span',
    cssProperty: 'grid-column',
    group: 'autoLayout',
    control: 'number',
    placeholder: '1',
    min: 1,
    tailwindPrefix: 'col-span',
    cssTransform: 'span {value} / span {value}',
    hiddenInV1: true,
  },
  {
    id: 'rowSpan',
    label: 'Row span',
    shortLabel: 'Row span',
    cssProperty: 'grid-row',
    group: 'autoLayout',
    control: 'number',
    placeholder: '1',
    min: 1,
    tailwindPrefix: 'row-span',
    cssTransform: 'span {value} / span {value}',
    hiddenInV1: true,
  },

  // ── Size ──────────────────────────────────────────────────────────────
  {
    id: 'width',
    label: 'Width',
    shortLabel: 'W',
    cssProperty: 'width',
    group: 'size',
    control: 'number',
    placeholder: '0',
    units: ['px', 'em', '%'],
    defaultUnit: 'px',
    tailwindPrefix: 'w',
  },
  {
    id: 'height',
    label: 'Height',
    shortLabel: 'H',
    cssProperty: 'height',
    group: 'size',
    control: 'number',
    placeholder: '0',
    units: ['px', 'em', '%'],
    defaultUnit: 'px',
    tailwindPrefix: 'h',
  },
  {
    id: 'minWidth',
    label: 'Min width',
    shortLabel: 'Min-W',
    cssProperty: 'min-width',
    group: 'size',
    control: 'number',
    placeholder: '0',
    units: ['px', 'rem', '%'],
    defaultUnit: 'px',
    tailwindPrefix: 'min-w',
  hiddenInV1: true,
  },
  {
    id: 'maxWidth',
    label: 'Max width',
    shortLabel: 'Max-W',
    cssProperty: 'max-width',
    group: 'size',
    control: 'number',
    placeholder: 'none',
    units: ['px', 'rem', '%', 'none'],
    defaultUnit: 'px',
    tailwindPrefix: 'max-w',
  hiddenInV1: true,
  },
  {
    id: 'minHeight',
    label: 'Min height',
    shortLabel: 'Min-H',
    cssProperty: 'min-height',
    group: 'size',
    control: 'number',
    placeholder: '0',
    units: ['px', 'rem', '%'],
    defaultUnit: 'px',
    tailwindPrefix: 'min-h',
  hiddenInV1: true,
  },
  {
    id: 'maxHeight',
    label: 'Max height',
    shortLabel: 'Max-H',
    cssProperty: 'max-height',
    group: 'size',
    control: 'number',
    placeholder: 'none',
    units: ['px', 'rem', '%', 'none'],
    defaultUnit: 'px',
    tailwindPrefix: 'max-h',
  hiddenInV1: true,
  },

  // ── Spacing ───────────────────────────────────────────────────────────
  {
    id: 'paddingTop',
    label: 'Padding top',
    shortLabel: 'PT',
    cssProperty: 'padding-top',
    group: 'spacing',
    control: 'number',
    placeholder: '16px',
    units: ['px'],
    defaultUnit: 'px',
    tailwindPrefix: 'pt',
  },
  {
    id: 'paddingRight',
    label: 'Padding right',
    shortLabel: 'PR',
    cssProperty: 'padding-right',
    group: 'spacing',
    control: 'number',
    placeholder: '16px',
    units: ['px'],
    defaultUnit: 'px',
    tailwindPrefix: 'pr',
  },
  {
    id: 'paddingBottom',
    label: 'Padding bottom',
    shortLabel: 'PB',
    cssProperty: 'padding-bottom',
    group: 'spacing',
    control: 'number',
    placeholder: '16px',
    units: ['px'],
    defaultUnit: 'px',
    tailwindPrefix: 'pb',
  },
  {
    id: 'paddingLeft',
    label: 'Padding left',
    shortLabel: 'PL',
    cssProperty: 'padding-left',
    group: 'spacing',
    control: 'number',
    placeholder: '16px',
    units: ['px'],
    defaultUnit: 'px',
    tailwindPrefix: 'pl',
  },
  {
    id: 'marginTop',
    label: 'Margin top',
    shortLabel: 'MT',
    cssProperty: 'margin-top',
    group: 'spacing',
    control: 'number',
    placeholder: '8px',
    units: ['px'],
    defaultUnit: 'px',
    tailwindPrefix: 'mt',
  },
  {
    id: 'marginRight',
    label: 'Margin right',
    shortLabel: 'MR',
    cssProperty: 'margin-right',
    group: 'spacing',
    control: 'number',
    placeholder: '8px',
    units: ['px'],
    defaultUnit: 'px',
    tailwindPrefix: 'mr',
  },
  {
    id: 'marginBottom',
    label: 'Margin bottom',
    shortLabel: 'MB',
    cssProperty: 'margin-bottom',
    group: 'spacing',
    control: 'number',
    placeholder: '8px',
    units: ['px'],
    defaultUnit: 'px',
    tailwindPrefix: 'mb',
  },
  {
    id: 'marginLeft',
    label: 'Margin left',
    shortLabel: 'ML',
    cssProperty: 'margin-left',
    group: 'spacing',
    control: 'number',
    placeholder: '8px',
    units: ['px'],
    defaultUnit: 'px',
    tailwindPrefix: 'ml',
  },

  // ── Appearance ────────────────────────────────────────────────────────
  {
    id: 'opacity',
    label: 'Opacity',
    shortLabel: 'Opacity',
    cssProperty: 'opacity',
    group: 'appearance',
    control: 'number',
    placeholder: '100',
    min: 0,
    max: 100,
    step: 1,
    units: ['%'],
    defaultUnit: '%',
    tailwindPrefix: 'opacity',
  },
  {
    id: 'mixBlendMode',
    label: 'Blending mode',
    shortLabel: 'Blend',
    cssProperty: 'mix-blend-mode',
    group: 'appearance',
    control: 'select',
    placeholder: 'normal',
    options: [
      { label: 'Normal', value: 'normal' },
      { label: 'Multiply', value: 'multiply' },
      { label: 'Screen', value: 'screen' },
      { label: 'Overlay', value: 'overlay' },
      { label: 'Darken', value: 'darken' },
      { label: 'Lighten', value: 'lighten' },
      { label: 'Color Dodge', value: 'color-dodge' },
      { label: 'Color Burn', value: 'color-burn' },
      { label: 'Hard Light', value: 'hard-light' },
      { label: 'Soft Light', value: 'soft-light' },
      { label: 'Difference', value: 'difference' },
      { label: 'Exclusion', value: 'exclusion' },
    ],
    tailwindPrefix: 'mix-blend',
  },
  {
    id: 'borderRadius',
    label: 'Border radius',
    shortLabel: 'Radius',
    cssProperty: 'border-radius',
    group: 'appearance',
    control: 'number',
    placeholder: '12px',
    units: ['px'],
    defaultUnit: 'px',
    tailwindPrefix: 'rounded',
  },
  {
    id: 'borderTopLeftRadius',
    label: 'Top-left radius',
    shortLabel: 'TL',
    cssProperty: 'border-top-left-radius',
    group: 'appearance',
    control: 'number',
    placeholder: '0px',
    units: ['px'],
    defaultUnit: 'px',
    tailwindPrefix: 'rounded-tl',
  },
  {
    id: 'borderTopRightRadius',
    label: 'Top-right radius',
    shortLabel: 'TR',
    cssProperty: 'border-top-right-radius',
    group: 'appearance',
    control: 'number',
    placeholder: '0px',
    units: ['px'],
    defaultUnit: 'px',
    tailwindPrefix: 'rounded-tr',
  },
  {
    id: 'borderBottomRightRadius',
    label: 'Bottom-right radius',
    shortLabel: 'BR',
    cssProperty: 'border-bottom-right-radius',
    group: 'appearance',
    control: 'number',
    placeholder: '0px',
    units: ['px'],
    defaultUnit: 'px',
    tailwindPrefix: 'rounded-br',
  },
  {
    id: 'borderBottomLeftRadius',
    label: 'Bottom-left radius',
    shortLabel: 'BL',
    cssProperty: 'border-bottom-left-radius',
    group: 'appearance',
    control: 'number',
    placeholder: '0px',
    units: ['px'],
    defaultUnit: 'px',
    tailwindPrefix: 'rounded-bl',
  },
  {
    id: 'overflow',
    label: 'Overflow',
    shortLabel: 'Overflow',
    cssProperty: 'overflow',
    group: 'appearance',
    control: 'select',
    placeholder: 'visible',
    options: [
      { label: 'Visible', value: 'visible',
  hiddenInV1: true },
      { label: 'Hidden', value: 'hidden' },
      { label: 'Scroll', value: 'scroll' },
      { label: 'Auto', value: 'auto' },
    ],
    tailwindPrefix: 'overflow',
  },
  {
    id: 'visibility',
    label: 'Visible',
    shortLabel: 'Vis',
    cssProperty: 'visibility',
    group: 'appearance',
    control: 'toggle',
    placeholder: 'visible',
    options: [
      { label: 'Yes', value: 'visible' },
      { label: 'No', value: 'hidden' },
    ],
    tailwindPrefix: 'visibility',
  },

  // ── Fill ──────────────────────────────────────────────────────────────
  {
    id: 'backgroundColor',
    label: 'Background',
    shortLabel: 'BG',
    cssProperty: 'background',
    group: 'fill',
    control: 'fill',
    placeholder: 'rgb(255, 255, 255)',
    tailwindPrefix: 'bg',
  },
  {
    id: 'backgroundImage',
    label: 'Background Image',
    shortLabel: 'Image',
    cssProperty: 'background-image',
    group: 'fill',
    control: 'text',
    placeholder: "url('./assets/image.png')",
    tailwindPrefix: 'bg',
    hiddenInV1: true,
  },
  {
    id: 'color',
    label: 'Text color',
    shortLabel: 'Text',
    cssProperty: 'color',
    group: 'fill',
    control: 'color',
    placeholder: 'rgb(17, 24, 39)',
    tailwindPrefix: 'text',
  },

  // ── Stroke / Border ──────────────────────────────────────────────────
  {
    id: 'borderColor',
    label: 'Border color',
    shortLabel: 'Color',
    cssProperty: 'border-color',
    group: 'stroke',
    control: 'color',
    placeholder: 'rgb(229, 231, 235)',
    tailwindPrefix: 'border',
  },
  {
    id: 'borderStyle',
    label: 'Border style',
    shortLabel: 'Style',
    cssProperty: 'border-style',
    group: 'stroke',
    control: 'select',
    placeholder: 'solid',
    options: [
      { label: 'None', value: 'none' },
      { label: 'Solid', value: 'solid' },
    ],
    tailwindPrefix: 'border',
  },
  {
    id: 'borderTopWidth',
    label: 'Border top',
    shortLabel: 'BT',
    cssProperty: 'border-top-width',
    group: 'stroke',
    control: 'number',
    placeholder: '1px',
    units: ['px'],
    defaultUnit: 'px',
    tailwindPrefix: 'border-t',
  },
  {
    id: 'borderRightWidth',
    label: 'Border right',
    shortLabel: 'BR',
    cssProperty: 'border-right-width',
    group: 'stroke',
    control: 'number',
    placeholder: '1px',
    units: ['px'],
    defaultUnit: 'px',
    tailwindPrefix: 'border-r',
  },
  {
    id: 'borderBottomWidth',
    label: 'Border bottom',
    shortLabel: 'BB',
    cssProperty: 'border-bottom-width',
    group: 'stroke',
    control: 'number',
    placeholder: '1px',
    units: ['px'],
    defaultUnit: 'px',
    tailwindPrefix: 'border-b',
  },
  {
    id: 'borderLeftWidth',
    label: 'Border left',
    shortLabel: 'BL',
    cssProperty: 'border-left-width',
    group: 'stroke',
    control: 'number',
    placeholder: '1px',
    units: ['px'],
    defaultUnit: 'px',
    tailwindPrefix: 'border-l',
  },
  {
    id: 'strokeDasharray',
    label: 'Stroke Dash Array',
    shortLabel: 'Dash',
    cssProperty: 'stroke-dasharray',
    group: 'stroke',
    control: 'text',
    placeholder: 'e.g. 4 4',
    tailwindPrefix: 'stroke',
  },

  // ── Typography ────────────────────────────────────────────────────────
  {
    id: 'fontFamily',
    label: 'Font family',
    shortLabel: 'Family',
    cssProperty: 'font-family',
    group: 'typography',
    control: 'select',
    placeholder: 'Inter, sans-serif',
    options: [
      { label: 'Inter', value: 'Inter, sans-serif' },
      { label: 'System Sans', value: 'system-ui, sans-serif' },
      { label: 'Helvetica Neue', value: '"Helvetica Neue", Arial, sans-serif' },
      { label: 'Georgia', value: 'Georgia, serif' },
      { label: 'Times New Roman', value: '"Times New Roman", serif' },
      { label: 'Monospace', value: '"SFMono-Regular", Menlo, Monaco, monospace' },
    ],
    tailwindPrefix: 'font',
  },
  {
    id: 'fontSize',
    label: 'Font size',
    shortLabel: 'Size',
    cssProperty: 'font-size',
    group: 'typography',
    control: 'number',
    placeholder: '16px',
    units: ['px', 'rem', 'em'],
    defaultUnit: 'px',
    tailwindPrefix: 'text',
  },
  {
    id: 'fontWeight',
    label: 'Font weight',
    shortLabel: 'Weight',
    cssProperty: 'font-weight',
    group: 'typography',
    control: 'select',
    placeholder: '400',
    options: [
      { label: 'Thin', value: '100' },
      { label: 'Extra Light', value: '200' },
      { label: 'Light', value: '300' },
      { label: 'Normal', value: '400' },
      { label: 'Medium', value: '500' },
      { label: 'Semi Bold', value: '600' },
      { label: 'Bold', value: '700' },
      { label: 'Extra Bold', value: '800' },
      { label: 'Black', value: '900' },
    ],
    tailwindPrefix: 'font',
  },
  {
    id: 'lineHeight',
    label: 'Line height',
    shortLabel: 'Leading',
    cssProperty: 'line-height',
    group: 'typography',
    control: 'number',
    placeholder: '24px',
    units: ['px', 'rem', 'em'],
    defaultUnit: 'px',
    tailwindPrefix: 'leading',
  },
  {
    id: 'letterSpacing',
    label: 'Letter spacing',
    shortLabel: 'Tracking',
    cssProperty: 'letter-spacing',
    group: 'typography',
    control: 'number',
    placeholder: '0px',
    units: ['px', '%'],
    defaultUnit: 'px',
    tailwindPrefix: 'tracking',
  },
  {
    id: 'textAlign',
    label: 'Text align',
    shortLabel: 'Align',
    cssProperty: 'text-align',
    group: 'typography',
    control: 'segmented',
    placeholder: 'left',
    options: [
      { label: 'Left', value: 'left' },
      { label: 'Center', value: 'center' },
      { label: 'Right', value: 'right' },
      { label: 'Justify', value: 'justify' },
    ],
    tailwindPrefix: 'text',
  },
  {
    id: 'textDecoration',
    label: 'Decoration',
    shortLabel: 'Decor',
    cssProperty: 'text-decoration',
    group: 'typography',
    control: 'select',
    placeholder: 'none',
    options: [
      { label: 'None', value: 'none' },
      { label: 'Underline', value: 'underline' },
      { label: 'Overline', value: 'overline' },
      { label: 'Line-through', value: 'line-through' },
    ],
    tailwindPrefix: 'decoration',
  },
  {
    id: 'textTransform',
    label: 'Transform',
    shortLabel: 'Case',
    cssProperty: 'text-transform',
    group: 'typography',
    control: 'select',
    placeholder: 'none',
    options: [
      { label: 'None', value: 'none' },
      { label: 'Uppercase', value: 'uppercase' },
      { label: 'Lowercase', value: 'lowercase' },
      { label: 'Capitalize', value: 'capitalize' },
    ],
    tailwindPrefix: 'text-transform',
  },
  {
    id: 'whiteSpace',
    label: 'White space',
    shortLabel: 'Wrap',
    cssProperty: 'white-space',
    group: 'typography',
    control: 'select',
    placeholder: 'normal',
    options: [
      { label: 'Normal', value: 'normal',
  hiddenInV1: true },
      { label: 'No wrap', value: 'nowrap' },
      { label: 'Pre', value: 'pre' },
      { label: 'Pre-wrap', value: 'pre-wrap' },
      { label: 'Pre-line', value: 'pre-line' },
    ],
    tailwindPrefix: 'whitespace',
  },
  {
    id: 'textOverflow',
    label: 'Text overflow',
    shortLabel: 'Overflow',
    cssProperty: 'text-overflow',
    group: 'typography',
    control: 'select',
    placeholder: 'clip',
    options: [
      { label: 'Clip', value: 'clip',
  hiddenInV1: true },
      { label: 'Ellipsis', value: 'ellipsis' },
    ],
    tailwindPrefix: 'text-overflow',
  },
  {
    id: 'wordBreak',
    label: 'Word break',
    shortLabel: 'Break',
    cssProperty: 'word-break',
    group: 'typography',
    control: 'select',
    placeholder: 'normal',
    options: [
      { label: 'Normal', value: 'normal',
  hiddenInV1: true },
      { label: 'Break all', value: 'break-all' },
      { label: 'Keep all', value: 'keep-all' },
      { label: 'Break word', value: 'break-word' },
    ],
    tailwindPrefix: 'break',
  },
  {
    id: 'overflowWrap',
    label: 'Overflow wrap',
    shortLabel: 'OvWrap',
    cssProperty: 'overflow-wrap',
    group: 'typography',
    control: 'select',
    placeholder: 'normal',
    options: [
      { label: 'Normal', value: 'normal',
  hiddenInV1: true },
      { label: 'Break word', value: 'break-word' },
      { label: 'Anywhere', value: 'anywhere' },
    ],
    tailwindPrefix: 'overflow-wrap',
  },
  {
    id: 'lineClamp',
    label: 'Line clamp',
    shortLabel: 'Clamp',
    cssProperty: '-webkit-line-clamp',
    group: 'typography',
    control: 'number',
    placeholder: 'none',
    min: 1,
    tailwindPrefix: 'line-clamp',
  hiddenInV1: true,
  },

  // ── Effects ───────────────────────────────────────────────────────────
  {
    id: 'boxShadow',
    label: 'Box shadow',
    shortLabel: 'Shadow',
    cssProperty: 'box-shadow',
    group: 'effects',
    control: 'text',
    placeholder: '0 1px 3px rgba(0,0,0,0.1)',
    tailwindPrefix: 'shadow',
  hiddenInV1: true,
  },
  {
    id: 'filter',
    label: 'Filter',
    shortLabel: 'Filter',
    cssProperty: 'filter',
    group: 'effects',
    control: 'text',
    placeholder: 'none',
    tailwindPrefix: 'filter',
  hiddenInV1: true,
  },
  {
    id: 'backdropFilter',
    label: 'Backdrop filter',
    shortLabel: 'Backdrop',
    cssProperty: 'backdrop-filter',
    group: 'effects',
    control: 'text',
    placeholder: 'none',
    tailwindPrefix: 'backdrop',
  hiddenInV1: true,
  },

  // ── Transition ────────────────────────────────────────────────────────
  {
    id: 'transitionProperty',
    label: 'Transition',
    shortLabel: 'Property',
    cssProperty: 'transition-property',
    group: 'transition',
    control: 'text',
    placeholder: 'none',
    tailwindPrefix: 'transition',
  hiddenInV1: true,
  },
  {
    id: 'transitionDuration',
    label: 'Duration',
    shortLabel: 'Duration',
    cssProperty: 'transition-duration',
    group: 'transition',
    control: 'number',
    placeholder: '0ms',
    units: ['ms', 's'],
    defaultUnit: 'ms',
    tailwindPrefix: 'duration',
  hiddenInV1: true,
  },
  {
    id: 'transitionTimingFunction',
    label: 'Easing',
    shortLabel: 'Ease',
    cssProperty: 'transition-timing-function',
    group: 'transition',
    control: 'select',
    placeholder: 'ease',
    options: [
      { label: 'Ease', value: 'ease',
  hiddenInV1: true },
      { label: 'Linear', value: 'linear' },
      { label: 'Ease in', value: 'ease-in' },
      { label: 'Ease out', value: 'ease-out' },
      { label: 'Ease in-out', value: 'ease-in-out' },
    ],
    tailwindPrefix: 'ease',
  },
  {
    id: 'transitionDelay',
    label: 'Delay',
    shortLabel: 'Delay',
    cssProperty: 'transition-delay',
    group: 'transition',
    control: 'number',
    placeholder: '0ms',
    units: ['ms', 's'],
    defaultUnit: 'ms',
    tailwindPrefix: 'delay',
  hiddenInV1: true,
  },

  // ── Layout (advanced) ────────────────────────────────────────────────
  {
    id: 'cursor',
    label: 'Cursor',
    shortLabel: 'Cursor',
    cssProperty: 'cursor',
    group: 'layout',
    control: 'select',
    placeholder: 'auto',
    options: [
      { label: 'Auto', value: 'auto',
  hiddenInV1: true },
      { label: 'Default', value: 'default' },
      { label: 'Pointer', value: 'pointer' },
      { label: 'Move', value: 'move' },
      { label: 'Text', value: 'text' },
      { label: 'Not Allowed', value: 'not-allowed' },
      { label: 'Grab', value: 'grab' },
    ],
    tailwindPrefix: 'cursor',
  },
  {
    id: 'pointerEvents',
    label: 'Pointer events',
    shortLabel: 'Pointer',
    cssProperty: 'pointer-events',
    group: 'layout',
    control: 'select',
    placeholder: 'auto',
    options: [
      { label: 'Auto', value: 'auto',
  hiddenInV1: true },
      { label: 'None', value: 'none' },
    ],
    tailwindPrefix: 'pointer-events',
  },
  {
    id: 'userSelect',
    label: 'User select',
    shortLabel: 'Select',
    cssProperty: 'user-select',
    group: 'layout',
    control: 'select',
    placeholder: 'auto',
    options: [
      { label: 'Auto', value: 'auto',
  hiddenInV1: true },
      { label: 'None', value: 'none' },
      { label: 'Text', value: 'text' },
      { label: 'All', value: 'all' },
    ],
    tailwindPrefix: 'select',
  },
] satisfies EditablePropertyDefinition[];

export const editablePropertyDefinitionMap = Object.fromEntries(
  editablePropertyDefinitions.map((definition) => [definition.id, definition])
) as Record<EditablePropertyId, EditablePropertyDefinition>;

export const editablePropertyGroupOrder = [
  'position',
  'autoLayout',
  'size',
  'spacing',
  'appearance',
  'fill',
  'stroke',
  'typography',
  'effects',
  'transition',
  'layout',
] as const satisfies EditablePropertyGroupId[];

export const editablePropertyGroupLabels: Record<EditablePropertyGroupId, string> = {
  position: 'Position',
  autoLayout: 'Auto Layout',
  size: 'Size',
  spacing: 'Spacing',
  appearance: 'Appearance',
  fill: 'Fill',
  stroke: 'Stroke',
  typography: 'Typography',
  effects: 'Effects',
  transition: 'Transition',
  layout: 'Advanced',
};

export const FOCUSED_PROPERTY_IDS = new Set<EditablePropertyId>([
  // Position & Size
  'positionType',
  'top',
  'left',
  'width',
  'height',
  // Auto Layout
  'display',
  'flexDirection',
  'flexWrap',
  'justifyContent',
  'alignItems',
  'alignSelf',
  'gap',
  'columnGap',
  'rowGap',
  'gridColumns',
  'gridRows',
  'flexGrow',
  'flexShrink',
  'flexBasis',
  'gridAutoFlow',
  'columnSpan',
  'rowSpan',
  // Spacing
  'paddingTop',
  'paddingRight',
  'paddingBottom',
  'paddingLeft',
  'marginTop',
  'marginRight',
  'marginBottom',
  'marginLeft',
  // Fill & Opacity
  'backgroundColor',
  'color',
  'opacity',
  // Border
  'borderColor',
  'borderStyle',
  'strokeDasharray',
  'borderTopWidth',
  'borderRightWidth',
  'borderBottomWidth',
  'borderLeftWidth',
  'borderRadius',
  'borderTopLeftRadius',
  'borderTopRightRadius',
  'borderBottomRightRadius',
  'borderBottomLeftRadius',
  // Typography
  'fontFamily',
  'fontSize',
  'fontWeight',
  'lineHeight',
  'letterSpacing',
  'textAlign',
  // Effects
  'boxShadow',
  'filter',
  'backdropFilter',
]);

export const focusedGroupOrder = [
  'positionSize',
  'autoLayout',
  'spacing',
  'fillOpacity',
  'border',
  'typography',
] as const satisfies FocusedGroupId[];

export const focusedGroupLabels: Record<FocusedGroupId, string> = {
  positionSize: 'Spacing',
  autoLayout: 'Layout',
  spacing: 'Spacing',
  fillOpacity: 'Fill',
  border: 'Border',
  typography: 'Typography',
  effects: 'Effects',
};

export const focusedGroupMembers: Record<FocusedGroupId, EditablePropertyId[]> = {
  positionSize: ['positionType', 'top', 'left', 'width', 'height', 'paddingTop', 'paddingRight', 'paddingBottom', 'paddingLeft', 'marginTop', 'marginRight', 'marginBottom', 'marginLeft'],
  autoLayout: ['display', 'flexDirection', 'flexWrap', 'justifyContent', 'alignItems', 'alignSelf', 'gap', 'columnGap', 'rowGap', 'gridColumns', 'gridRows', 'flexGrow', 'flexShrink', 'flexBasis', 'gridAutoFlow', 'columnSpan', 'rowSpan'],
  spacing: [
    'paddingTop',
    'paddingRight',
    'paddingBottom',
    'paddingLeft',
    'marginTop',
    'marginRight',
    'marginBottom',
    'marginLeft',
  ],
  fillOpacity: ['backgroundColor', 'opacity', 'mixBlendMode', 'borderRadius', 'borderTopLeftRadius', 'borderTopRightRadius', 'borderBottomRightRadius', 'borderBottomLeftRadius'],
  border: ['borderColor', 'borderStyle', 'strokeDasharray', 'borderTopWidth', 'borderRightWidth', 'borderBottomWidth', 'borderLeftWidth'],
  typography: ['fontFamily', 'fontSize', 'fontWeight', 'color', 'lineHeight', 'letterSpacing', 'textAlign'],
  effects: ['boxShadow', 'filter', 'backdropFilter'],
};
